name: books_to_read
description: "An app with a list of books to read."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  easy_localization: ^3.0.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.3
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  retrofit_generator: ^8.0.6

flutter:
  uses-material-design: true

  assets:
    - assets/translations/